In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, models
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.isnull().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [ ]:
df['Age'].fillna(df['Age'].median(),inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)
df['Cabin'].fillna(df['Cabin'].mode()[0],inplace=True)

/tmp/ipython-input-3437686986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)
/tmp/ipython-input-3437686986.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try u

In [ ]:
df['Embarked']=df['Embarked'].map({'S':0,'C':1,'Q':2})
df['Sex']=df['Sex'].map({'male':0,'female':1})
df['Cabin']=df['Cabin'].map({'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6})

In [ ]:
X=df[['Age','Pclass','SibSp','Parch','Fare','Embarked','Sex']]
y=df[['Survived']]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)

In [ ]:
X_test.head(3)

,Age,Pclass,SibSp,Parch,Fare,Embarked,Sex
837,28.0,3,0,0,8.0500,0,0
334,28.0,1,1,0,133.6500,0,1
849,28.0,1,1,0,89.1042,1,1


In [ ]:
X_train.sample(5)

,Age,Pclass,SibSp,Parch,Fare,Embarked,Sex
788,1.0,3,1,2,20.5750,0,0
374,3.0,3,3,1,21.0750,0,1
692,28.0,3,0,0,56.4958,0,0
384,28.0,3,0,0,7.8958,0,0
114,17.0,3,0,0,14.4583,1,1


In [ ]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_test

array([[-0.11023411,  0.83022982, -0.47682185, ..., -0.49609507,
        -0.55969464, -0.74015275],
       [-0.11023411, -1.56298327,  0.40728533, ...,  2.16770849,
        -0.55969464,  1.35107247],
       [-0.11023411, -1.56298327,  0.40728533, ...,  1.22295323,
         1.03431569,  1.35107247],
       ...,
       [-0.41361118,  0.83022982, -0.47682185, ..., -0.46534256,
        -0.55969464, -0.74015275],
       [ 0.49652005,  0.83022982,  0.40728533, ..., -0.2977944 ,
        -0.55969464,  1.35107247],
       [-0.03438984, -1.56298327, -0.47682185, ..., -0.0305657 ,
        -0.55969464, -0.74015275]])

In [ ]:
model=models.Sequential([
    layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history=model.fit(X_train,y_train,epochs=50,
                  batch_size=32,validation_data=(X_test,y_test))

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 6s 28ms/step - accuracy: 0.6183 - loss: 0.7019 - val_accuracy: 0.6089 - val_loss: 0.6723
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6271 - loss: 0.6592 - val_accuracy: 0.6089 - val_loss: 0.6434
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6127 - loss: 0.6367 - val_accuracy: 0.6145 - val_loss: 0.6206
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6585 - loss: 0.6002 - val_accuracy: 0.6369 - val_loss: 0.5971
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6810 - loss: 0.5839 - val_accuracy: 0.7095 - val_loss: 0.5751
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7389 - loss: 0.5449 - val_accuracy: 0.7430 - val_loss: 0.5532
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7618 - loss: 0.5367 - val_accuracy: 0.7542 - val_loss: 0.5353
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7927 - loss: 0.5036 - val_accuracy: 0.7989 - val_

In [ ]:
loss,acc= model.evaluate(X_test,y_test)
loss,acc

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8801 - loss: 0.3954 


(0.4350269138813019, 0.8435754179954529)

In [ ]:
X_test[:3],y_test[:3]


(array([[-0.11023411,  0.83022982, -0.47682185, -0.50442349, -0.49609507,
         -0.55969464, -0.74015275],
        [-0.11023411, -1.56298327,  0.40728533, -0.50442349,  2.16770849,
         -0.55969464,  1.35107247],
        [-0.11023411, -1.56298327,  0.40728533, -0.50442349,  1.22295323,
          1.03431569,  1.35107247]]),
      Survived
 837         0
 334         1
 849         1)

In [ ]:
model.predict(X_test[:3])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step


array([[0.09705959],
       [0.991369  ],
       [0.99280995]], dtype=float32)